name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Create dummy setting file
        run: |
          cat << EOF > ./src/settings.cpp
          const char* SETTINGS_WIFI_SSID = "";
          const char* SETTINGS_WIFI_PASS = "";
          const char* SETTINGS_ADDRESS_TIMETABLE_JSON = "";
          EOF
      - name: Run PlatformIO
        run: platformio run
